version: '3.9'
services:
  customer-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
  migration:
    image: customer-management-api
    command: >
      sh -c "sleep 10 && configs:
      dotnet ef database update --project CustomerManagement.WebApi.csproj --startup-project CustomerManagement.WebApi.csproj --context ApplicationDbContext --verbose"
